# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: example-use-case
  annotations:
    github.com/project-slug: AI-Agent-Incubator-Month/repo-name
  description: |
    your description
    We achieved the following goals:
      1) goal 1
      2) goal 2
  labels:
    industry: Automotive
    valuechain: Research_and_Development
    subsegment: Research_and_Ideation
spec:
  type: usecase
  lifecycle: experimental
  owner: example-use-case-owners
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: example-use-case-owners
  description: Maintainers for contacting
spec:
  type: team
  profile:
    displayName: Example Use Case Maintainers
    email: team42@example.com
    picture: http://de-mucbddemo01.apps.ce.capgemini.com:1414/_static/logo.png
    parent: capability
  children: []
  members: [firstname.lastname] # see below, refer to metadata.name of the users
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: firstname.lastname
spec:
  profile:
    displayName: Firstname Lastname
    email: firstname.lastname@capgemini.com
  memberOf: [data_engineering]
